module.exports =[
    {id:1,
        name:'John Doe',
        password:'123456',
    },
    {id:2,
        name:'Jane Doe',
        password:'654321',
    },
    {id:3,
        name:'Jim Doe',
        password:'abcdef',
    },      
    {id:4,
        name:'Jack Doe',
        password:'qwerty',
    },
    {id:5,
        name:'Jill Doe',
        password:'asdfgh',
    },
    {id:6,
        name:'Joe Doe',
        password:'123abc',
    },
       
];